name: CI

on: [push]

jobs:
  build-with-nix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}-${{ hashFiles('package.yaml') }}-${{ hashFiles('Setup.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name:
      run: |
        nix-env -iA nixos.stack
    - name: Run tests
      run: |
        stack test
